version: "3.9"

name: log_viewer
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"

  app:
    build: .
    command: >
      bash -c "psql postgresql://${DB_USER}:${DB_PASS}@db:5432/postgres -c 'drop database if exists ${DB_NAME} with(force)'
      && psql postgresql://${DB_USER}:${DB_PASS}@db:5432/postgres -c 'create database ${DB_NAME}'
      && plackup -p 3000 -M Devel::Camelcadedb /opt/app/bin/app.psgi"
    restart: no
    volumes:
      - .:/opt/app
    ports:
      - "9000:3000"
    working_dir: /opt/app
    environment:
      PERL5LIB: /opt/app/lib
      PERL5_DEBUG_AUTOSTART: ${DEBUG}
      PERL5_DEBUG_ROLE: client
      PERL5_DEBUG_HOST: host.docker.internal
      PERL5_DEBUG_PORT: 40000
    depends_on:
      - db

  nginx:
    image: nginx
    volumes:
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "8080:8080"
    environment:
      - NGINX_POXY_PASS=http://app:3000
    depends_on:
      - app

